import type { SharedSliceModel } from "@prismicio/client";

import { builders, loadFile, writeFile as magicastWriteFile } from "magicast";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import { readConfig, updateConfig } from "./config";
import { exists } from "./file";
import { FrameworkAdapter } from "./framework-adapter";
import {
	sliceSimulatorPageTemplate,
	sliceTemplate,
} from "./framework-nuxt.templates";
import { getNpmPackageVersion } from "./packageJson";
import { dedent } from "./string";

const NUXT_PRISMIC = "@nuxtjs/prismic";

export class NuxtFramework extends FrameworkAdapter {
	async getDependencies(): Promise<Record<string, string>> {
		return {
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			[NUXT_PRISMIC]: `^${await getNpmPackageVersion(NUXT_PRISMIC)}`,
		};
	}

	async initProject(): Promise<void> {
		await super.initProject();

		await this.#configureNuxtModule();
		await this.#createSliceSimulatorPage();
		await this.#moveOrDeleteAppVue();
		await this.#modifySliceLibraryPath();
	}

	async createSliceComponent(
		model: SharedSliceModel,
		sliceDirectory: URL,
	): Promise<{ componentPath: URL }> {
		const componentPath = new URL("index.vue", sliceDirectory);
		const contents = sliceTemplate({
			name: model.name,
			typescript: await this.checkIsTypeScriptProject(),
		});
		await writeFile(componentPath, contents);
		return { componentPath };
	}

	getSliceImportPath(relativeDirectory: string): string {
		return `./${relativeDirectory}/index.vue`;
	}

	async getDefaultSliceLibraryPath(_projectRoot: URL): Promise<URL> {
		const srcDir = await this.#getSrcDir();
		return new URL("slices/", srcDir);
	}

	protected override async generateSliceLibraryIndexContents(
		slices: { library: URL; directory: URL; model: SharedSliceModel }[],
	): Promise<string> {
		const componentLines = await Promise.all(
			slices.map(async (slice) => {
				const relativeDirectory = relative(
					fileURLToPath(slice.library),
					fileURLToPath(slice.directory),
				);
				return `${slice.model.id}: defineAsyncComponent(() => import("./${relativeDirectory}/index.vue"))`;
			}),
		);

		return dedent`
			// Code generated by Prismic. DO NOT EDIT.

			import { defineAsyncComponent } from "vue";
			import { defineSliceZoneComponents } from "@prismicio/vue";

			export const components = defineSliceZoneComponents({
				${componentLines.join(",\n")}
			});
		`;
	}

	async #getSrcDir(): Promise<URL> {
		const projectRoot = await this.getProjectRoot();
		const appDir = new URL("app/", projectRoot);
		if (await exists(appDir)) return appDir;
		const srcDir = new URL("src/", projectRoot);
		if (await exists(srcDir)) return srcDir;
		return projectRoot;
	}

	async #configureNuxtModule(): Promise<void> {
		const projectRoot = await this.getProjectRoot();

		let configUrl = new URL("nuxt.config.js", projectRoot);
		if (!(await exists(configUrl))) {
			configUrl = new URL("nuxt.config.ts", projectRoot);
		}
		if (!(await exists(configUrl))) {
			return;
		}

		const filepath = fileURLToPath(configUrl);
		const mod = await loadFile(filepath);
		const config =
			mod.exports.default.$type === "function-call"
				? mod.exports.default.$args[0]
				: mod.exports.default;

		// Check if @nuxtjs/prismic is already registered
		let hasInlinedConfiguration = false;
		const hasPrismicModuleRegistered = (config.modules || []).find(
			(registration: string | [string, unknown]) => {
				if (typeof registration === "string") {
					return registration === NUXT_PRISMIC;
				} else if (Array.isArray(registration)) {
					hasInlinedConfiguration = !!registration[1];
					return registration[0] === NUXT_PRISMIC;
				}
				return false;
			},
		);

		if (!hasPrismicModuleRegistered) {
			config.modules ||= [];
			config.modules.push(NUXT_PRISMIC);
		}

		// Append Prismic module configuration if not inlined
		if (!hasInlinedConfiguration) {
			mod.imports.$prepend({
				from: "./prismic.config.json",
				imported: "repositoryName",
			});

			config.prismic ||= {};
			config.prismic.endpoint = builders.raw("repositoryName");
		}

		await magicastWriteFile(mod, filepath);
	}

	async #createSliceSimulatorPage(): Promise<void> {
		const projectRoot = await this.getProjectRoot();
		const typescript = await this.checkIsTypeScriptProject();

		// Check for existing pages directories in priority order
		const appPagesDir = new URL("app/pages/", projectRoot);
		const srcPagesDir = new URL("src/pages/", projectRoot);
		const pagesDir = new URL("pages/", projectRoot);

		let targetDir: URL;
		if (await exists(appPagesDir)) {
			targetDir = appPagesDir;
		} else if (await exists(srcPagesDir)) {
			targetDir = srcPagesDir;
		} else if (await exists(pagesDir)) {
			targetDir = pagesDir;
		} else {
			targetDir = new URL("pages/", await this.#getSrcDir());
		}

		const filePath = new URL("slice-simulator.vue", targetDir);

		if (await exists(filePath)) {
			return;
		}

		const contents = sliceSimulatorPageTemplate({ typescript });
		await mkdir(targetDir, { recursive: true });
		await writeFile(filePath, contents);
	}

	async #moveOrDeleteAppVue(): Promise<void> {
		const srcDir = await this.#getSrcDir();
		const appVuePath = new URL("app.vue", srcDir);

		if (!(await exists(appVuePath))) {
			return;
		}

		const contents = await readFile(appVuePath, "utf8");

		if (!contents.includes("<NuxtWelcome")) {
			return;
		}

		const indexVuePath = new URL("pages/index.vue", srcDir);

		if (!(await exists(indexVuePath))) {
			await mkdir(new URL(".", indexVuePath), { recursive: true });
			await writeFile(indexVuePath, contents);
		}

		await rm(appVuePath);
	}

	async #modifySliceLibraryPath(): Promise<void> {
		const projectRoot = await this.getProjectRoot();
		const hasAppDir = await exists(new URL("app/", projectRoot));
		const hasSrcDir = await exists(new URL("src/", projectRoot));

		if (!hasAppDir && !hasSrcDir) {
			return;
		}

		const configResult = await readConfig();
		if (!configResult.ok) return;

		const libraries = configResult.config.libraries;
		if (
			!libraries ||
			JSON.stringify(libraries) !== JSON.stringify(["./slices"])
		) {
			return;
		}

		// Only modify if the default library has no slices yet
		const slices = await this.getSlices();
		if (slices.length > 0) {
			return;
		}

		const newLibrary = hasAppDir ? "./app/slices" : "./src/slices";
		await updateConfig({ libraries: [newLibrary] });
	}
}
