import type { CustomType, SharedSlice } from "@prismicio/types-internal/lib/customtypes";

import { pascalCase } from "change-case";
import { createRequire } from "node:module";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import { Adapter } from ".";
import { buildRoutePath } from "../config";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, findPackageJson, getNpmPackageVersion } from "../lib/packageJson";
import { dedent } from "../lib/string";
import { appendTrailingSlash } from "../lib/url";
import { checkIsTypeScriptProject, findProjectRoot } from "../project";
import {
	pageTemplate,
	revalidateRouteTemplate,
	exitPreviewRouteTemplate,
	previewRouteTemplate,
	prismicIOFileTemplate,
	sliceSimulatorPageTemplate,
	sliceTemplate,
} from "./nextjs.templates";

export class NextJsAdapter extends Adapter {
	readonly id = "next";

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			"@prismicio/react": `^${await getNpmPackageVersion("@prismicio/react")}`,
			"@prismicio/next": `^${await getNpmPackageVersion("@prismicio/next")}`,
		});
		await createPrismicIoFile();
		await createSliceSimulatorPage();
		await createPreviewRoute();
		await createExitPreviewRoute();
		await createRevalidateRoute();
	}

	onProjectInitialized(): void {}

	async onSliceCreated(model: SharedSlice, library: URL): Promise<void> {
		const sliceDirectoryName = pascalCase(model.name);
		const sliceDirectory = new URL(sliceDirectoryName, appendTrailingSlash(library));

		const extension = await getJsFileExtension();
		const componentPath = new URL(`index.${extension}x`, appendTrailingSlash(sliceDirectory));
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(componentPath, contents);
	}

	onSliceUpdated(): void {}

	onSliceDeleted(): void {}

	async onCustomTypeCreated(model: CustomType): Promise<void> {
		if (model.format === "page") await createPageFile(model);
	}

	onCustomTypeUpdated(): void {}

	onCustomTypeDeleted(): void {}

	async createSliceIndexFile(library: URL): Promise<void> {
		const allSlices = await this.getSlices();
		const slices = allSlices.filter((slice) => slice.library.href === library.href);
		const imports = slices.map((slice) => {
			const componentName = pascalCase(slice.model.name);
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `import ${componentName} from "./${relativeDirectory}";`;
		});
		const componentLines = slices.map((slice) => {
			const componentName = pascalCase(slice.model.name);
			return `${slice.model.id}: ${componentName}`;
		});
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			${imports.join("\n")}

			export const components = {
				${componentLines.join(",\n")}
			};
		`;
		const extension = await getJsFileExtension();
		const filename = `index.${extension}`;
		const indexPath = new URL(filename, library);
		await writeFileRecursive(indexPath, contents);
	}

	async getDefaultSliceLibrary(): Promise<URL> {
		const projectRoot = await findProjectRoot();
		const hasSrcDirectory = await checkHasSrc();
		const defaultSliceLibrary = new URL(hasSrcDirectory ? "src/slices/" : "slices/", projectRoot);
		return defaultSliceLibrary;
	}
}

async function createRevalidateRoute(): Promise<void> {
	const appRouter = await checkUsesAppRouter();
	if (!appRouter) return;

	const sourceRoot = await getSourceRoot();
	const extension = await getJsFileExtension();
	const filePath = new URL(`app/api/revalidate/route.${extension}`, sourceRoot);
	if (await exists(filePath)) return;

	const version = await getNextJsVersion();
	const major = Number.parseInt(version.split(".")[0]);
	const supportsCacheLife = major >= 16;

	const contents = revalidateRouteTemplate({ supportsCacheLife });
	await writeFileRecursive(filePath, contents);
}

async function createExitPreviewRoute(): Promise<void> {
	const appRouter = await checkUsesAppRouter();
	const sourceRoot = await getSourceRoot();
	const extension = await getJsFileExtension();
	const filePath = new URL(
		appRouter ? `app/api/exit-preview/route.${extension}` : `pages/api/exit-preview.${extension}`,
		sourceRoot,
	);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();

	const contents = exitPreviewRouteTemplate({ typescript, appRouter });
	await writeFileRecursive(filePath, contents);
}

async function createPreviewRoute(): Promise<void> {
	const appRouter = await checkUsesAppRouter();
	const sourceRoot = await getSourceRoot();
	const extension = await getJsFileExtension();
	const filePath = new URL(
		appRouter ? `app/api/preview/route.${extension}` : `pages/api/preview.${extension}`,
		sourceRoot,
	);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();

	const contents = previewRouteTemplate({ typescript, appRouter });
	await writeFileRecursive(filePath, contents);
}

async function createSliceSimulatorPage(): Promise<void> {
	const appRouter = await checkUsesAppRouter();
	const sourceRoot = await getSourceRoot();
	const extension = `${await getJsFileExtension()}x`;
	const filePath = new URL(
		appRouter ? `app/slice-simulator/page.${extension}` : `pages/slice-simulator.${extension}`,
		sourceRoot,
	);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();

	const contents = sliceSimulatorPageTemplate({ typescript, appRouter });
	await writeFileRecursive(filePath, contents);
}

async function createPrismicIoFile(): Promise<void> {
	const extension = await getJsFileExtension();
	const sourceRoot = await getSourceRoot();
	const filePath = new URL(`prismicio.${extension}`, sourceRoot);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();
	const appRouter = await checkUsesAppRouter();
	const hasSrcDirectory = await checkHasSrc();

	const contents = prismicIOFileTemplate({
		typescript,
		appRouter,
		hasSrcDirectory,
	});
	await writeFileRecursive(filePath, contents);
}

async function createPageFile(model: CustomType): Promise<void> {
	const routePath = buildRoutePath(model)
		.split("/")
		.filter(Boolean)
		.map((segment) => (segment.startsWith(":") ? `[${segment.slice(1)}]` : segment))
		.join("/");
	const sourceRoot = await getSourceRoot();
	const extension = `${await getJsFileExtension()}x`;
	const usesAppRouter = await checkUsesAppRouter();
	const pageFilePath = usesAppRouter
		? new URL(`app/${routePath}/page.${extension}`, sourceRoot)
		: new URL(`pages/${routePath || "index"}.${extension}`, sourceRoot);

	if (await exists(pageFilePath)) return;

	const contents = pageTemplate({
		model,
		routePath,
		typescript: await checkIsTypeScriptProject(),
		appRouter: usesAppRouter,
	});
	await writeFileRecursive(pageFilePath, contents);
}

async function checkUsesAppRouter() {
	const sourceDirectory = await getSourceRoot();
	const appDirectory = new URL("app/", sourceDirectory);
	const usesAppRouter = await exists(appDirectory);
	return usesAppRouter;
}

async function getSourceRoot() {
	const projectRoot = await findProjectRoot();
	const hasSrcDirectory = await checkHasSrc();
	if (hasSrcDirectory) return new URL("src/", projectRoot);
	return projectRoot;
}

async function checkHasSrc(): Promise<boolean> {
	const projectRoot = await findProjectRoot();
	const srcDirectory = new URL("src/", projectRoot);
	return exists(srcDirectory);
}

async function getJsFileExtension() {
	const isTypeScriptProject = await checkIsTypeScriptProject();
	const jsFileExtension = isTypeScriptProject ? "ts" : "js";
	return jsFileExtension;
}

async function getNextJsVersion() {
	const packageJsonPath = await findPackageJson();
	const require = createRequire(packageJsonPath);
	const { version } = require("next/package.json");
	return version;
}
