import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import type { DynamicCustomTypeModel, SharedSliceModel } from "@prismicio/types-internal";
import { pascalCase } from "change-case";

import {
	Adapter,
	checkSourceContains,
	getInstalledMajor,
	getJsFileExtension,
	writeFileIfMissing,
} from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, getNpmPackageVersion } from "../lib/packageJson";
import { dedent, formatObjectKey } from "../lib/string";
import { checkIsTypeScriptProject, findProjectRoot } from "../project";
import {
	exitPreviewRouteTemplate,
	pageTemplate,
	previewRouteTemplate,
	prismicIOFileTemplate,
	revalidateRouteTemplate,
	sliceSimulatorPageTemplate,
	sliceTemplate,
} from "./nextjs.templates";

export class NextJsAdapter extends Adapter {
	readonly id = "next";

	readonly environmentEnvVarName = "NEXT_PUBLIC_PRISMIC_ENVIRONMENT";

	readonly localPreviewConfig = {
		name: "Development",
		websiteURL: "http://localhost:3000",
		resolverPath: "/api/preview",
	};

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			"@prismicio/react": `^${await getNpmPackageVersion("@prismicio/react")}`,
			"@prismicio/next": `^${await getNpmPackageVersion("@prismicio/next")}`,
		});

		const sourceRoot = await getSourceRoot();
		const extension = await getJsFileExtension();
		const typescript = await checkIsTypeScriptProject();
		const appRouter = await checkUsesAppRouter();

		await writeFileIfMissing(
			new URL(`prismicio.${extension}`, sourceRoot),
			prismicIOFileTemplate({ typescript, appRouter, hasSrcDirectory: await checkHasSrc() }),
		);
		await writeFileIfMissing(
			new URL(
				appRouter
					? `app/slice-simulator/page.${extension}x`
					: `pages/slice-simulator.${extension}x`,
				sourceRoot,
			),
			sliceSimulatorPageTemplate({ typescript, appRouter }),
		);
		await writeFileIfMissing(
			new URL(
				appRouter ? `app/api/preview/route.${extension}` : `pages/api/preview.${extension}`,
				sourceRoot,
			),
			previewRouteTemplate({ typescript, appRouter }),
		);
		await writeFileIfMissing(
			new URL(
				appRouter
					? `app/api/exit-preview/route.${extension}`
					: `pages/api/exit-preview.${extension}`,
				sourceRoot,
			),
			exitPreviewRouteTemplate({ typescript, appRouter }),
		);
		if (appRouter) {
			await writeFileIfMissing(
				new URL(`app/api/revalidate/route.${extension}`, sourceRoot),
				revalidateRouteTemplate({ supportsCacheLife: (await getInstalledMajor("next")) >= 16 }),
			);
		}
	}

	async getPreviewComponentInstructions(): Promise<string | undefined> {
		if (await checkSourceContains("PrismicPreview")) return;

		const sourceDirectory = (await checkHasSrc()) ? "src/" : "";
		const extension = `${await getJsFileExtension()}x`;

		if (await checkUsesAppRouter()) {
			return dedent`
				Action required: add <PrismicPreview> to your root layout.

				Previews do not work until you do this, and the CLI cannot edit your
				layout for you. Make the change now.

				Add the lines marked + to ${sourceDirectory}app/layout.${extension}:

				+ import { PrismicPreview } from "@prismicio/next";
				+ import { repositoryName } from "@/prismicio";

				  export default function RootLayout({ children }) {
				    return (
				      <html lang="en">
				        <body>{children}</body>
				+       <PrismicPreview repositoryName={repositoryName} />
				      </html>
				    );
				  }

				Run \`prismic docs view nextjs\` for details.
			`;
		}

		return dedent`
			Action required: add <PrismicPreview> to your app.

			Previews do not work until you do this, and the CLI cannot edit your app
			for you. Make the change now.

			Add the lines marked + to ${sourceDirectory}pages/_app.${extension}:

			+ import { PrismicPreview } from "@prismicio/next/pages";
			+ import { repositoryName } from "@/prismicio";

			  export default function App({ Component, pageProps }) {
			    return (
			+     <>
			        <Component {...pageProps} />
			+       <PrismicPreview repositoryName={repositoryName} />
			+     </>
			    );
			  }

			Run \`prismic docs view nextjs\` for details.
		`;
	}

	async createSliceIndexFile(library: URL): Promise<void> {
		const slices = (await this.getSlices()).filter((slice) => slice.library.href === library.href);
		const imports = slices.map((slice) => {
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `import ${pascalCase(slice.model.name)} from "./${relativeDirectory}";`;
		});
		const componentLines = slices.map(
			(slice) => `${formatObjectKey(slice.model.id)}: ${pascalCase(slice.model.name)}`,
		);
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			${imports.join("\n")}

			export const components = {
				${componentLines.join(",\n")}
			};
		`;
		await writeFileRecursive(new URL(`index.${await getJsFileExtension()}`, library), contents);
	}

	protected async getDefaultSliceLibrary(): Promise<URL> {
		return new URL((await checkHasSrc()) ? "src/slices/" : "slices/", await findProjectRoot());
	}

	protected async createSliceComponent(model: SharedSliceModel, directory: URL): Promise<void> {
		const contents = sliceTemplate({
			name: model.name,
			id: model.id,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(new URL(`index.${await getJsFileExtension()}x`, directory), contents);
	}

	protected async createPageFile(model: DynamicCustomTypeModel, routePath: string): Promise<void> {
		const sourceRoot = await getSourceRoot();
		const extension = `${await getJsFileExtension()}x`;
		const appRouter = await checkUsesAppRouter();
		const path = appRouter
			? new URL(`app/${routePath}/page.${extension}`, sourceRoot)
			: new URL(`pages/${routePath || "index"}.${extension}`, sourceRoot);
		const typescript = await checkIsTypeScriptProject();
		await writeFileIfMissing(path, pageTemplate({ model, routePath, typescript, appRouter }));
	}
}

async function checkUsesAppRouter(): Promise<boolean> {
	return exists(new URL("app/", await getSourceRoot()));
}

async function getSourceRoot(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	return (await checkHasSrc()) ? new URL("src/", projectRoot) : projectRoot;
}

async function checkHasSrc(): Promise<boolean> {
	return exists(new URL("src/", await findProjectRoot()));
}
