import { readFile, rm } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import type { DynamicCustomTypeModel, SharedSliceModel } from "@prismicio/types-internal";
import { x } from "tinyexec";

import { Adapter, getJsFileExtension, writeFileIfMissing } from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, getNpmPackageVersion } from "../lib/packageJson";
import { dedent, formatObjectKey } from "../lib/string";
import { checkIsTypeScriptProject, findProjectRoot, readConfig, updateConfig } from "../project";
import { pageTemplate, sliceSimulatorPageTemplate, sliceTemplate } from "./nuxt.templates";

const NUXT_PRISMIC = "@nuxtjs/prismic";

export class NuxtAdapter extends Adapter {
	readonly id = "nuxt";

	readonly environmentEnvVarName = "NUXT_PUBLIC_PRISMIC_ENVIRONMENT";

	readonly localPreviewConfig = {
		name: "Development",
		websiteURL: "http://localhost:3000",
		resolverPath: "/preview",
	};

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			[NUXT_PRISMIC]: `^${await getNpmPackageVersion(NUXT_PRISMIC)}`,
		});
		await configureNuxtModule();
		await writeFileIfMissing(
			new URL("slice-simulator.vue", await getPagesDir()),
			sliceSimulatorPageTemplate({ typescript: await checkIsTypeScriptProject() }),
		);
		await moveOrDeleteAppVue();
		await this.modifySliceLibraryPath();
	}

	async getPreviewComponentInstructions(): Promise<string | undefined> {
		const moduleStep =
			!(await checkNuxtConfigHasModule()) &&
			dedent`
				Action required: add "${NUXT_PRISMIC}" to modules in nuxt.config.

				The CLI could not register the module for you. Prismic does not work
				until you do this. Make the change now.

				  export default defineNuxtConfig({
				    modules: [
				+     "${NUXT_PRISMIC}",
				    ],
				  });
			`;

		return [moduleStep].filter(Boolean).join("\n\n") || undefined;
	}

	async createSliceIndexFile(library: URL): Promise<void> {
		const slices = (await this.getSlices()).filter((slice) => slice.library.href === library.href);
		const componentLines = slices.map((slice) => {
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `${formatObjectKey(slice.model.id)}: defineAsyncComponent(() => import("./${relativeDirectory}/index.vue"))`;
		});
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			import { defineAsyncComponent } from "vue";
			import { defineSliceZoneComponents } from "@prismicio/vue";

			export const components = defineSliceZoneComponents({
				${componentLines.join(",\n")}
			});
		`;
		await writeFileRecursive(new URL(`index.${await getJsFileExtension()}`, library), contents);
	}

	protected async getDefaultSliceLibrary(): Promise<URL> {
		return new URL("slices/", await getSrcDir());
	}

	protected async createSliceComponent(model: SharedSliceModel, directory: URL): Promise<void> {
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(new URL("index.vue", directory), contents);
	}

	protected async createPageFile(model: DynamicCustomTypeModel, routePath: string): Promise<void> {
		await writeFileIfMissing(
			new URL(`${routePath || "index"}.vue`, await getPagesDir()),
			pageTemplate({ model, typescript: await checkIsTypeScriptProject() }),
		);
	}

	private async modifySliceLibraryPath(): Promise<void> {
		const projectRoot = await findProjectRoot();
		const hasAppDir = await exists(new URL("app/", projectRoot));
		const hasSrcDir = await exists(new URL("src/", projectRoot));
		if (!hasAppDir && !hasSrcDir) return;

		let config;
		try {
			config = await readConfig();
		} catch {
			return;
		}
		if (JSON.stringify(config.libraries) !== JSON.stringify(["./slices"])) return;

		// Only modify if the default library has no slices yet
		if ((await this.getSlices()).length > 0) return;

		await updateConfig({ libraries: [hasAppDir ? "./app/slices" : "./src/slices"] });
	}
}

async function getSrcDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	const appDir = new URL("app/", projectRoot);
	if (await exists(appDir)) return appDir;
	const srcDir = new URL("src/", projectRoot);
	if (await exists(srcDir)) return srcDir;
	return projectRoot;
}

async function getPagesDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	for (const path of ["app/pages/", "src/pages/", "pages/"]) {
		const pagesDir = new URL(path, projectRoot);
		if (await exists(pagesDir)) return pagesDir;
	}
	return new URL("pages/", await getSrcDir());
}

async function configureNuxtModule(): Promise<void> {
	if (await checkNuxtConfigHasModule()) return;

	// Piped stdio keeps nuxi from prompting. It can exit 0 without editing the
	// config, so the instructions check the config instead of the exit code.
	try {
		await x("nuxi", ["module", "add", NUXT_PRISMIC, "--skipInstall"], {
			nodeOptions: { cwd: fileURLToPath(await findProjectRoot()) },
		});
	} catch {}
}

async function checkNuxtConfigHasModule(): Promise<boolean> {
	const projectRoot = await findProjectRoot();
	for (const filename of ["nuxt.config.ts", "nuxt.config.js"]) {
		const contents = await readFile(new URL(filename, projectRoot), "utf8").catch(() => "");
		if (contents.includes(NUXT_PRISMIC)) return true;
	}
	return false;
}

async function moveOrDeleteAppVue(): Promise<void> {
	const srcDir = await getSrcDir();
	const appVuePath = new URL("app.vue", srcDir);
	if (!(await exists(appVuePath))) return;

	const contents = await readFile(appVuePath, "utf8");
	if (!contents.includes("<NuxtWelcome")) return;

	await writeFileIfMissing(new URL("pages/index.vue", srcDir), contents);
	await rm(appVuePath);
}
