import type { CustomType, SharedSlice } from "@prismicio/types-internal/lib/customtypes";

import { loadFile, writeFile } from "magicast";
import { readFile, rm } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import { Adapter, getJsFileExtension, writeFileIfMissing } from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, getNpmPackageVersion } from "../lib/packageJson";
import { dedent, formatObjectKey } from "../lib/string";
import { checkIsTypeScriptProject, findProjectRoot, readConfig, updateConfig } from "../project";
import { pageTemplate, sliceSimulatorPageTemplate, sliceTemplate } from "./nuxt.templates";

const NUXT_PRISMIC = "@nuxtjs/prismic";

export class NuxtAdapter extends Adapter {
	readonly id = "nuxt";

	readonly environmentEnvVarName = "NUXT_PUBLIC_PRISMIC_ENVIRONMENT";

	readonly localPreviewConfig = {
		name: "Development",
		websiteURL: "http://localhost:3000",
		resolverPath: "/preview",
	};

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			[NUXT_PRISMIC]: `^${await getNpmPackageVersion(NUXT_PRISMIC)}`,
		});
		await configureNuxtModule();
		await writeFileIfMissing(
			new URL("slice-simulator.vue", await getPagesDir()),
			sliceSimulatorPageTemplate({ typescript: await checkIsTypeScriptProject() }),
		);
		await moveOrDeleteAppVue();
		await this.modifySliceLibraryPath();
	}

	async getPreviewComponentInstructions(): Promise<undefined> {}

	async createSliceIndexFile(library: URL): Promise<void> {
		const slices = (await this.getSlices()).filter((slice) => slice.library.href === library.href);
		const componentLines = slices.map((slice) => {
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `${formatObjectKey(slice.model.id)}: defineAsyncComponent(() => import("./${relativeDirectory}/index.vue"))`;
		});
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			import { defineAsyncComponent } from "vue";
			import { defineSliceZoneComponents } from "@prismicio/vue";

			export const components = defineSliceZoneComponents({
				${componentLines.join(",\n")}
			});
		`;
		await writeFileRecursive(new URL(`index.${await getJsFileExtension()}`, library), contents);
	}

	protected async getDefaultSliceLibrary(): Promise<URL> {
		return new URL("slices/", await getSrcDir());
	}

	protected async createSliceComponent(model: SharedSlice, directory: URL): Promise<void> {
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(new URL("index.vue", directory), contents);
	}

	protected async createPageFile(model: CustomType, routePath: string): Promise<void> {
		await writeFileIfMissing(
			new URL(`${routePath || "index"}.vue`, await getPagesDir()),
			pageTemplate({ model, typescript: await checkIsTypeScriptProject() }),
		);
	}

	private async modifySliceLibraryPath(): Promise<void> {
		const projectRoot = await findProjectRoot();
		const hasAppDir = await exists(new URL("app/", projectRoot));
		const hasSrcDir = await exists(new URL("src/", projectRoot));
		if (!hasAppDir && !hasSrcDir) return;

		let config;
		try {
			config = await readConfig();
		} catch {
			return;
		}
		if (JSON.stringify(config.libraries) !== JSON.stringify(["./slices"])) return;

		// Only modify if the default library has no slices yet
		if ((await this.getSlices()).length > 0) return;

		await updateConfig({ libraries: [hasAppDir ? "./app/slices" : "./src/slices"] });
	}
}

async function getSrcDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	const appDir = new URL("app/", projectRoot);
	if (await exists(appDir)) return appDir;
	const srcDir = new URL("src/", projectRoot);
	if (await exists(srcDir)) return srcDir;
	return projectRoot;
}

async function getPagesDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	for (const path of ["app/pages/", "src/pages/", "pages/"]) {
		const pagesDir = new URL(path, projectRoot);
		if (await exists(pagesDir)) return pagesDir;
	}
	return new URL("pages/", await getSrcDir());
}

async function configureNuxtModule(): Promise<void> {
	const projectRoot = await findProjectRoot();
	let configUrl = new URL("nuxt.config.js", projectRoot);
	if (!(await exists(configUrl))) configUrl = new URL("nuxt.config.ts", projectRoot);
	if (!(await exists(configUrl))) return;

	const filepath = fileURLToPath(configUrl);
	const mod = await loadFile(filepath);
	const config =
		mod.exports.default.$type === "function-call"
			? mod.exports.default.$args[0]
			: mod.exports.default;

	// `find`, not `some`: magicast's array proxy returns the wrong result for `some`.
	const isRegistered = (config.modules || []).find((registration: string | [string, unknown]) =>
		Array.isArray(registration) ? registration[0] === NUXT_PRISMIC : registration === NUXT_PRISMIC,
	);
	if (!isRegistered) {
		config.modules ||= [];
		config.modules.push(NUXT_PRISMIC);
	}

	await writeFile(mod, filepath);
}

async function moveOrDeleteAppVue(): Promise<void> {
	const srcDir = await getSrcDir();
	const appVuePath = new URL("app.vue", srcDir);
	if (!(await exists(appVuePath))) return;

	const contents = await readFile(appVuePath, "utf8");
	if (!contents.includes("<NuxtWelcome")) return;

	await writeFileIfMissing(new URL("pages/index.vue", srcDir), contents);
	await rm(appVuePath);
}
