import type { CustomType, SharedSlice } from "@prismicio/types-internal/lib/customtypes";

import { pascalCase } from "change-case";
import { loadFile, writeFile as magicastWriteFile } from "magicast";
import { readFile, rm } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import { Adapter } from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, getNpmPackageVersion } from "../lib/packageJson";
import { dedent } from "../lib/string";
import { appendTrailingSlash } from "../lib/url";
import { buildRoutePath, readConfig, updateConfig } from "../project";
import { checkIsTypeScriptProject, findProjectRoot } from "../project";
import { pageTemplate, sliceSimulatorPageTemplate, sliceTemplate } from "./nuxt.templates";

const NUXT_PRISMIC = "@nuxtjs/prismic";

export class NuxtAdapter extends Adapter {
	readonly id = "nuxt";

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			[NUXT_PRISMIC]: `^${await getNpmPackageVersion(NUXT_PRISMIC)}`,
		});
		await configureNuxtModule();
		await createSliceSimulatorPage();
		await moveOrDeleteAppVue();
		await modifySliceLibraryPath(this);
	}

	onProjectInitialized(): void {}

	async onSliceCreated(model: SharedSlice, library: URL): Promise<void> {
		const sliceDirectoryName = pascalCase(model.name);
		const sliceDirectory = new URL(sliceDirectoryName, appendTrailingSlash(library));

		const componentPath = new URL("index.vue", appendTrailingSlash(sliceDirectory));
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(componentPath, contents);
	}

	onSliceUpdated(): void {}

	onSliceDeleted(): void {}

	async onCustomTypeCreated(model: CustomType): Promise<void> {
		if (model.format === "page") await createPageFile(model);
	}

	onCustomTypeUpdated(): void {}

	onCustomTypeDeleted(): void {}

	async createSliceIndexFile(library: URL): Promise<void> {
		const allSlices = await this.getSlices();
		const slices = allSlices.filter((slice) => slice.library.href === library.href);
		const componentLines = slices.map((slice) => {
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `${slice.model.id}: defineAsyncComponent(() => import("./${relativeDirectory}/index.vue"))`;
		});
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			import { defineAsyncComponent } from "vue";
			import { defineSliceZoneComponents } from "@prismicio/vue";

			export const components = defineSliceZoneComponents({
				${componentLines.join(",\n")}
			});
		`;
		const extension = await getJsFileExtension();
		const filename = `index.${extension}`;
		const indexPath = new URL(filename, library);
		await writeFileRecursive(indexPath, contents);
	}

	async getDefaultSliceLibrary(): Promise<URL> {
		const srcDir = await getSrcDir();
		return new URL("slices/", srcDir);
	}

	async getDefaultCustomTypeLibrary(): Promise<URL> {
		const projectRoot = await findProjectRoot();
		const defaultCustomTypeLibrary = new URL("customtypes/", projectRoot)
		return defaultCustomTypeLibrary;
	}
}

async function getSrcDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();
	const appDir = new URL("app/", projectRoot);
	if (await exists(appDir)) return appDir;
	const srcDir = new URL("src/", projectRoot);
	if (await exists(srcDir)) return srcDir;
	return projectRoot;
}

async function configureNuxtModule(): Promise<void> {
	const projectRoot = await findProjectRoot();

	let configUrl = new URL("nuxt.config.js", projectRoot);
	if (!(await exists(configUrl))) {
		configUrl = new URL("nuxt.config.ts", projectRoot);
	}
	if (!(await exists(configUrl))) {
		return;
	}

	const filepath = fileURLToPath(configUrl);
	const mod = await loadFile(filepath);
	const config =
		mod.exports.default.$type === "function-call"
			? mod.exports.default.$args[0]
			: mod.exports.default;

	// Check if @nuxtjs/prismic is already registered
	const hasPrismicModuleRegistered = (config.modules || []).find(
		(registration: string | [string, unknown]) => {
			if (typeof registration === "string") {
				return registration === NUXT_PRISMIC;
			} else if (Array.isArray(registration)) {
				return registration[0] === NUXT_PRISMIC;
			}
			return false;
		},
	);

	if (!hasPrismicModuleRegistered) {
		config.modules ||= [];
		config.modules.push(NUXT_PRISMIC);
	}

	await magicastWriteFile(mod, filepath);
}

async function getPagesDir(): Promise<URL> {
	const projectRoot = await findProjectRoot();

	const appPagesDir = new URL("app/pages/", projectRoot);
	const srcPagesDir = new URL("src/pages/", projectRoot);
	const pagesDir = new URL("pages/", projectRoot);

	if (await exists(appPagesDir)) return appPagesDir;
	if (await exists(srcPagesDir)) return srcPagesDir;
	if (await exists(pagesDir)) return pagesDir;
	return new URL("pages/", await getSrcDir());
}

async function createSliceSimulatorPage(): Promise<void> {
	const typescript = await checkIsTypeScriptProject();
	const targetDir = await getPagesDir();

	const filePath = new URL("slice-simulator.vue", targetDir);

	if (await exists(filePath)) {
		return;
	}

	const contents = sliceSimulatorPageTemplate({ typescript });
	await writeFileRecursive(filePath, contents);
}

async function moveOrDeleteAppVue(): Promise<void> {
	const srcDir = await getSrcDir();
	const appVuePath = new URL("app.vue", srcDir);

	if (!(await exists(appVuePath))) {
		return;
	}

	const contents = await readFile(appVuePath, "utf8");

	if (!contents.includes("<NuxtWelcome")) {
		return;
	}

	const indexVuePath = new URL("pages/index.vue", srcDir);

	if (!(await exists(indexVuePath))) {
		await writeFileRecursive(indexVuePath, contents);
	}

	await rm(appVuePath);
}

async function modifySliceLibraryPath(adapter: NuxtAdapter): Promise<void> {
	const projectRoot = await findProjectRoot();
	const hasAppDir = await exists(new URL("app/", projectRoot));
	const hasSrcDir = await exists(new URL("src/", projectRoot));

	if (!hasAppDir && !hasSrcDir) {
		return;
	}

	let config;
	try {
		config = await readConfig();
	} catch {
		return;
	}

	const libraries = config.libraries;
	if (!libraries || JSON.stringify(libraries) !== JSON.stringify(["./slices"])) {
		return;
	}

	// Only modify if the default library has no slices yet
	const slices = await adapter.getSlices();
	if (slices.length > 0) {
		return;
	}

	const newLibrary = hasAppDir ? "./app/slices" : "./src/slices";
	await updateConfig({ libraries: [newLibrary] });
}

async function createPageFile(model: CustomType): Promise<void> {
	const routePath = buildRoutePath(model)
		.split("/")
		.filter(Boolean)
		.map((segment) => (segment.startsWith(":") ? `[${segment.slice(1)}]` : segment))
		.join("/");
	const pagesDir = await getPagesDir();
	const pageFilePath = new URL(`${routePath || "index"}.vue`, pagesDir);

	if (await exists(pageFilePath)) return;

	const contents = pageTemplate({
		model,
		typescript: await checkIsTypeScriptProject(),
	});
	await writeFileRecursive(pageFilePath, contents);
}

async function getJsFileExtension(): Promise<string> {
	const isTypeScriptProject = await checkIsTypeScriptProject();
	return isTypeScriptProject ? "ts" : "js";
}
