import type { CustomType, SharedSlice } from "@prismicio/types-internal/lib/customtypes";

import { pascalCase } from "change-case";
import { loadFile } from "magicast";
import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import { Adapter } from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { reportAction } from "../lib/logger";
import { addDependencies, findPackageJson, getNpmPackageVersion } from "../lib/packageJson";
import { dedent } from "../lib/string";
import { appendTrailingSlash } from "../lib/url";
import { buildRoutePath } from "../project";
import { checkIsTypeScriptProject, findProjectRoot } from "../project";
import {
	pageServerTemplate,
	pageTemplate,
	previewAPIRouteTemplate,
	prismicIOFileTemplate,
	rootLayoutTemplate,
	sliceSimulatorPageTemplate,
	sliceTemplate,
} from "./sveltekit.templates";

export class SvelteKitAdapter extends Adapter {
	readonly id = "sveltekit";

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			"@prismicio/svelte": `^${await getNpmPackageVersion("@prismicio/svelte")}`,
		});
		await createPrismicIoFile();
		await createSliceSimulatorPage();
		await createPreviewRouteMatcher();
		await createPreviewAPIRoute();
		await createPreviewRouteDirectory();
		await createRootLayoutServerFile();
		await createRootLayoutFile();
		await modifyViteConfig();
	}

	onProjectInitialized(): void {}

	async onSliceCreated(model: SharedSlice, library: URL): Promise<void> {
		const sliceDirectoryName = pascalCase(model.name);
		const sliceDirectory = new URL(sliceDirectoryName, appendTrailingSlash(library));

		const componentPath = new URL("index.svelte", appendTrailingSlash(sliceDirectory));
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
			version: await getSvelteMajor(),
		});
		await writeFileRecursive(componentPath, contents);
		reportAction({ type: "file-created", url: componentPath });
	}

	onSliceUpdated(): void {}

	onSliceDeleted(): void {}

	async onCustomTypeCreated(model: CustomType): Promise<void> {
		if (model.format === "page") await createPageFile(model);
	}

	onCustomTypeUpdated(): void {}

	onCustomTypeDeleted(): void {}

	async createSliceIndexFile(library: URL): Promise<void> {
		const allSlices = await this.getSlices();
		const slices = allSlices.filter((slice) => slice.library.href === library.href);
		const imports = slices.map((slice) => {
			const componentName = pascalCase(slice.model.name);
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `import ${componentName} from "./${relativeDirectory}/index.svelte";`;
		});
		const componentLines = slices.map((slice) => {
			const componentName = pascalCase(slice.model.name);
			return `${slice.model.id}: ${componentName}`;
		});
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			${imports.join("\n")}

			export const components = {
				${componentLines.join(",\n")}
			};
		`;
		const extension = await getJsFileExtension();
		const filename = `index.${extension}`;
		const indexPath = new URL(filename, library);
		await writeFileRecursive(indexPath, contents);
		reportAction({ type: "file-updated", url: indexPath });
	}

	async getDefaultSliceLibrary(): Promise<URL> {
		const projectRoot = await findProjectRoot();
		return new URL("src/lib/slices/", projectRoot);
	}
}

async function createPrismicIoFile(): Promise<void> {
	const extension = await getJsFileExtension();
	const projectRoot = await findProjectRoot();
	const filePath = new URL(`src/lib/prismicio.${extension}`, projectRoot);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();
	const contents = prismicIOFileTemplate({ typescript });
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createSliceSimulatorPage(): Promise<void> {
	const projectRoot = await findProjectRoot();
	const filePath = new URL("src/routes/slice-simulator/+page.svelte", projectRoot);
	if (await exists(filePath)) return;

	const contents = sliceSimulatorPageTemplate({
		version: await getSvelteMajor(),
	});
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createPreviewRouteMatcher(): Promise<void> {
	const extension = await getJsFileExtension();
	const projectRoot = await findProjectRoot();
	const filePath = new URL(`src/params/preview.${extension}`, projectRoot);
	if (await exists(filePath)) return;

	const contents = dedent`
		export function match(param) {
			return param === 'preview';
		}
	`;
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createPreviewAPIRoute(): Promise<void> {
	const extension = await getJsFileExtension();
	const projectRoot = await findProjectRoot();
	const filePath = new URL(`src/routes/api/preview/+server.${extension}`, projectRoot);
	if (await exists(filePath)) return;

	const typescript = await checkIsTypeScriptProject();
	const contents = previewAPIRouteTemplate({ typescript });
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createPreviewRouteDirectory(): Promise<void> {
	const projectRoot = await findProjectRoot();
	const filePath = new URL("src/routes/[[preview=preview]]/README.md", projectRoot);
	if (await exists(filePath)) return;

	const contents = dedent`
		This directory adds support for optional \`/preview\` routes. Do not remove this directory.

		All routes within this directory will be served using the following URLs:

		- \`/example-route\` (prerendered)
		- \`/preview/example-route\` (server-rendered)

		See <https://prismic.io/docs/svelte-preview> for more information.
	`;
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createRootLayoutServerFile(): Promise<void> {
	const extension = await getJsFileExtension();
	const projectRoot = await findProjectRoot();
	const filePath = new URL(`src/routes/+layout.server.${extension}`, projectRoot);
	if (await exists(filePath)) return;

	const contents = dedent`
		export const prerender = "auto";
	`;
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createRootLayoutFile(): Promise<void> {
	const projectRoot = await findProjectRoot();
	const filePath = new URL("src/routes/+layout.svelte", projectRoot);
	if (await exists(filePath)) return;

	const contents = rootLayoutTemplate({
		version: await getSvelteMajor(),
	});
	await writeFileRecursive(filePath, contents);
	reportAction({ type: "file-created", url: filePath });
}

async function createPageFile(model: CustomType): Promise<void> {
	const routePath = buildRoutePath(model)
		.split("/")
		.filter(Boolean)
		.map((segment) => (segment.startsWith(":") ? `[${segment.slice(1)}]` : segment))
		.join("/");
	const projectRoot = await findProjectRoot();
	const extension = await getJsFileExtension();
	const fullRoutePath = new URL(`src/routes/[[preview=preview]]/${routePath}/`, projectRoot);

	const pageFilePath = new URL("+page.svelte", fullRoutePath);
	if (!(await exists(pageFilePath))) {
		const contents = pageTemplate({
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(pageFilePath, contents);
		reportAction({ type: "file-created", url: pageFilePath });
	}

	const serverFilePath = new URL(`+page.server.${extension}`, fullRoutePath);
	if (!(await exists(serverFilePath))) {
		const contents = pageServerTemplate({
			model,
			typescript: await checkIsTypeScriptProject(),
		});
		await writeFileRecursive(serverFilePath, contents);
		reportAction({ type: "file-created", url: serverFilePath });
	}
}

async function modifyViteConfig(): Promise<void> {
	const projectRoot = await findProjectRoot();
	let configUrl = new URL("vite.config.js", projectRoot);
	if (!(await exists(configUrl))) {
		configUrl = new URL("vite.config.ts", projectRoot);
	}
	if (!(await exists(configUrl))) {
		return;
	}

	const filepath = configUrl.pathname;
	const mod = await loadFile(filepath);
	if (mod.exports.default.$type !== "function-call") {
		return;
	}

	const config = mod.exports.default.$args[0];
	config.server ??= {};
	config.server.fs ??= {};
	config.server.fs.allow ??= [];
	if (!config.server.fs.allow.includes("./prismic.config.json")) {
		config.server.fs.allow.push("./prismic.config.json");
	}

	const contents = mod.generate().code.replace(/\n\s*\n(?=\s*server:)/, "\n");
	await writeFile(configUrl, contents);
	reportAction({ type: "file-updated", url: configUrl });
}

async function getJsFileExtension(): Promise<string> {
	const isTypeScriptProject = await checkIsTypeScriptProject();
	return isTypeScriptProject ? "ts" : "js";
}

async function getSvelteMajor(): Promise<number> {
	const packageJsonPath = await findPackageJson();
	const require = createRequire(packageJsonPath);
	const { version } = require("svelte/package.json");
	const major = Number.parseInt(version.split(".")[0]);
	if (Number.isNaN(major)) return Infinity;
	return major;
}
