import { writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import type { DynamicCustomTypeModel, SharedSliceModel } from "@prismicio/types-internal";
import { pascalCase } from "change-case";
import { loadFile } from "magicast";

import {
	Adapter,
	checkSourceContains,
	getInstalledMajor,
	getJsFileExtension,
	type PageFile,
	writeFileIfMissing,
} from ".";
import { exists, writeFileRecursive } from "../lib/file";
import { addDependencies, getNpmPackageVersion } from "../lib/packageJson";
import { dedent, formatObjectKey } from "../lib/string";
import { checkIsTypeScriptProject, findProjectRoot } from "../project";
import {
	pageServerTemplate,
	pageTemplate,
	previewAPIRouteTemplate,
	prismicIOFileTemplate,
	rootLayoutTemplate,
	sliceSimulatorPageTemplate,
	sliceTemplate,
} from "./sveltekit.templates";

export class SvelteKitAdapter extends Adapter {
	readonly id = "sveltekit";

	readonly environmentEnvVarName = "PUBLIC_PRISMIC_ENVIRONMENT";

	readonly localPreviewConfig = {
		name: "Development",
		websiteURL: "http://localhost:5173",
		resolverPath: "/api/preview",
	};

	async setupProject(): Promise<void> {
		await addDependencies({
			"@prismicio/client": `^${await getNpmPackageVersion("@prismicio/client")}`,
			"@prismicio/svelte": `^${await getNpmPackageVersion("@prismicio/svelte")}`,
		});

		const projectRoot = await findProjectRoot();
		const extension = await getJsFileExtension();
		const typescript = await checkIsTypeScriptProject();
		const version = await getInstalledMajor("svelte");

		await writeFileIfMissing(
			new URL(`src/lib/prismicio.${extension}`, projectRoot),
			prismicIOFileTemplate({ typescript }),
		);
		await writeFileIfMissing(
			new URL("src/routes/slice-simulator/+page.svelte", projectRoot),
			sliceSimulatorPageTemplate({ version }),
		);
		await writeFileIfMissing(
			new URL(`src/params/preview.${extension}`, projectRoot),
			dedent`
				export function match(param) {
					return param === 'preview';
				}
			`,
		);
		await writeFileIfMissing(
			new URL(`src/routes/api/preview/+server.${extension}`, projectRoot),
			previewAPIRouteTemplate({ typescript }),
		);
		await writeFileIfMissing(
			new URL("src/routes/[[preview=preview]]/README.md", projectRoot),
			dedent`
				This directory adds support for optional \`/preview\` routes. Do not remove this directory.

				All routes within this directory will be served using the following URLs:

				- \`/example-route\` (prerendered)
				- \`/preview/example-route\` (server-rendered)

				See <https://prismic.io/docs/svelte-preview> for more information.
			`,
		);
		await writeFileIfMissing(
			new URL(`src/routes/+layout.server.${extension}`, projectRoot),
			'export const prerender = "auto";',
		);
		await writeFileIfMissing(
			new URL("src/routes/+layout.svelte", projectRoot),
			rootLayoutTemplate({ version }),
		);
		await modifyViteConfig();
	}

	async getPreviewComponentInstructions(): Promise<string | undefined> {
		if (await checkSourceContains("PrismicPreview")) return;

		const children = (await getInstalledMajor("svelte")) <= 4 ? "<slot />" : "{@render children()}";

		return dedent`
			Action required: add <PrismicPreview> to your root layout.

			Previews do not work until you do this, and the CLI cannot edit your
			layout for you. Make the change now.

			Add the lines marked + to src/routes/+layout.svelte:

			  <script>
			+   import { PrismicPreview } from "@prismicio/svelte/kit";
			+   import { repositoryName } from "$lib/prismicio";
			  </script>

			  ${children}
			+ <PrismicPreview {repositoryName} />

			Run \`prismic docs view sveltekit\` for details.
		`;
	}

	async createSliceIndexFile(library: URL): Promise<void> {
		const slices = (await this.getSlices()).filter((slice) => slice.library.href === library.href);
		const imports = slices.map((slice) => {
			const relativeDirectory = relative(fileURLToPath(library), fileURLToPath(slice.directory));
			return `import ${pascalCase(slice.model.name)} from "./${relativeDirectory}/index.svelte";`;
		});
		const componentLines = slices.map(
			(slice) => `${formatObjectKey(slice.model.id)}: ${pascalCase(slice.model.name)}`,
		);
		const contents = dedent`
			// Code generated by Prismic. DO NOT EDIT.

			${imports.join("\n")}

			export const components = {
				${componentLines.join(",\n")}
			};
		`;
		await writeFileRecursive(new URL(`index.${await getJsFileExtension()}`, library), contents);
	}

	protected async getDefaultSliceLibrary(): Promise<URL> {
		return new URL("src/lib/slices/", await findProjectRoot());
	}

	protected async createSliceComponent(model: SharedSliceModel, directory: URL): Promise<void> {
		const contents = sliceTemplate({
			name: model.name,
			typescript: await checkIsTypeScriptProject(),
			version: await getInstalledMajor("svelte"),
		});
		await writeFileRecursive(new URL("index.svelte", directory), contents);
	}

	protected async getPageFiles(
		model: DynamicCustomTypeModel,
		routePath: string,
	): Promise<PageFile[]> {
		const routeDirectory = new URL(
			`src/routes/[[preview=preview]]/${routePath}/`,
			await findProjectRoot(),
		);
		const typescript = await checkIsTypeScriptProject();
		return [
			{ path: new URL("+page.svelte", routeDirectory), contents: pageTemplate({ typescript }) },
			{
				path: new URL(`+page.server.${await getJsFileExtension()}`, routeDirectory),
				contents: pageServerTemplate({ model, typescript }),
			},
		];
	}
}

async function modifyViteConfig(): Promise<void> {
	const projectRoot = await findProjectRoot();
	let configUrl = new URL("vite.config.js", projectRoot);
	if (!(await exists(configUrl))) configUrl = new URL("vite.config.ts", projectRoot);
	if (!(await exists(configUrl))) return;

	const mod = await loadFile(configUrl.pathname);
	if (mod.exports.default.$type !== "function-call") return;

	const config = mod.exports.default.$args[0];
	config.server ??= {};
	config.server.fs ??= {};
	config.server.fs.allow ??= [];
	if (!config.server.fs.allow.includes("./prismic.config.json")) {
		config.server.fs.allow.push("./prismic.config.json");
	}

	await writeFile(configUrl, mod.generate().code.replace(/\n\s*\n(?=\s*server:)/, "\n"));
}
