import type { CustomType, Link } from "@prismicio/types-internal/lib/customtypes";

import { readFile, writeFile } from "node:fs/promises";
import { parseArgs } from "node:util";
import * as v from "valibot";

import { buildTypes } from "./codegen-types";
import { findUpward } from "./lib/file";
import { stringify } from "./lib/json";
import { humanReadable } from "./lib/string";

const HELP = `
Add a link field to an existing page type.

USAGE
  prismic page-type add-field link <type-id> <field-id> [flags]

ARGUMENTS
  type-id                  Page type identifier (required)
  field-id                 Field identifier (required)

Types are generated by default after changes. Use --no-types to skip.

FLAGS
  -t, --tab string         Target tab (default: first existing tab, or "Main")
  -l, --label string       Display label for the field (inferred from field-id if omitted)
  -p, --placeholder string Placeholder text
      --variation string   Slice variations (can be used multiple times)
      --allow-text         Allow text with link
      --allow-target-blank Allow opening link in new tab
      --repeatable         Allow multiple links
      --types string   Output file for generated types (default: "prismicio-types.d.ts")
      --no-types       Skip type generation
  -h, --help               Show help for command

EXAMPLES
  prismic page-type add-field link homepage button
  prismic page-type add-field link homepage cta --allow-text
  prismic page-type add-field link homepage cta --variation Primary --variation Secondary
  prismic page-type add-field link homepage links --repeatable
`.trim();

const CustomTypeSchema = v.object({
	id: v.string(),
	label: v.string(),
	repeatable: v.boolean(),
	status: v.boolean(),
	format: v.string(),
	json: v.record(v.string(), v.record(v.string(), v.unknown())),
});

export async function pageTypeAddFieldLink(): Promise<void> {
	const {
		values: {
			help,
			tab,
			label,
			placeholder,
			variation,
			"allow-text": allowText,
			"allow-target-blank": allowTargetBlank,
			repeatable,
			types,
			"no-types": noTypes,
		},
		positionals: [typeId, fieldId],
	} = parseArgs({
		args: process.argv.slice(5), // skip: node, script, "page-type", "add-field", "link"
		options: {
			tab: { type: "string", short: "t" },
			label: { type: "string", short: "l" },
			placeholder: { type: "string", short: "p" },
			variation: { type: "string", multiple: true },
			"allow-text": { type: "boolean" },
			"allow-target-blank": { type: "boolean" },
			repeatable: { type: "boolean" },
			types: { type: "string" },
			"no-types": { type: "boolean" },
			help: { type: "boolean", short: "h" },
		},
		allowPositionals: true,
	});

	if (help) {
		console.info(HELP);
		return;
	}

	if (!typeId) {
		console.error("Missing required argument: type-id\n");
		console.error("Usage: prismic page-type add-field link <type-id> <field-id>");
		process.exitCode = 1;
		return;
	}

	if (!fieldId) {
		console.error("Missing required argument: field-id\n");
		console.error("Usage: prismic page-type add-field link <type-id> <field-id>");
		process.exitCode = 1;
		return;
	}

	// Find the page type file
	const projectRoot = await findUpward("package.json");
	if (!projectRoot) {
		console.error("Could not find project root (no package.json found)");
		process.exitCode = 1;
		return;
	}

	const modelPath = new URL(`customtypes/${typeId}/index.json`, projectRoot);

	// Read and parse the model
	let model: CustomType;
	try {
		const contents = await readFile(modelPath, "utf8");
		const result = v.safeParse(CustomTypeSchema, JSON.parse(contents));
		if (!result.success) {
			console.error(`Invalid page type model: ${modelPath.href}`);
			process.exitCode = 1;
			return;
		}
		model = result.output as CustomType;
	} catch (error) {
		if (error instanceof Error && "code" in error && error.code === "ENOENT") {
			console.error(`Page type not found: ${typeId}\n`);
			console.error(`Create it first with: prismic page-type create ${typeId}`);
			process.exitCode = 1;
			return;
		}
		if (error instanceof Error) {
			console.error(`Failed to read page type: ${error.message}`);
		} else {
			console.error("Failed to read page type");
		}
		process.exitCode = 1;
		return;
	}

	// Determine target tab
	const existingTabs = Object.keys(model.json);
	const targetTab = tab ?? existingTabs[0] ?? "Main";

	// Initialize tab if it doesn't exist
	if (!model.json[targetTab]) {
		model.json[targetTab] = {};
	}

	// Check if field already exists in any tab
	for (const [tabName, tabFields] of Object.entries(model.json)) {
		if (tabFields[fieldId]) {
			console.error(`Field "${fieldId}" already exists in tab "${tabName}"`);
			process.exitCode = 1;
			return;
		}
	}

	// Build field definition
	const fieldDefinition: Link = {
		type: "Link",
		config: {
			label: label ?? humanReadable(fieldId),
			...(placeholder && { placeholder }),
			...(variation && variation.length > 0 && { variants: variation }),
			...(allowText && { allowText: true }),
			...(allowTargetBlank && { allowTargetBlank: true }),
			...(repeatable && { repeat: true }),
		},
	};

	// Add field to model
	model.json[targetTab][fieldId] = fieldDefinition;

	// Write updated model
	try {
		await writeFile(modelPath, stringify(model));
	} catch (error) {
		if (error instanceof Error) {
			console.error(`Failed to update page type: ${error.message}`);
		} else {
			console.error("Failed to update page type");
		}
		process.exitCode = 1;
		return;
	}

	console.info(`Added field "${fieldId}" (Link) to "${targetTab}" tab in ${typeId}`);

	if (!noTypes) {
		try {
			await buildTypes({ output: types });
			console.info(`Updated types in ${types ?? "prismicio-types.d.ts"}`);
		} catch (error) {
			console.warn(`Could not generate types: ${error instanceof Error ? error.message : error}`);
		}
	}

	console.info();
	console.info("Next: Add more fields with `prismic page-type add-field`");
	console.info("      Run `prismic status` when done to find next steps");
}
