import type { CustomType, DynamicSlices } from "@prismicio/types-internal/lib/customtypes";

import { readFile, writeFile } from "node:fs/promises";
import { parseArgs } from "node:util";
import * as v from "valibot";

import { buildTypes } from "./codegen-types";
import { findUpward } from "./lib/file";
import { stringify } from "./lib/json";

const HELP = `
Disconnect a shared slice from a page type's slice zone.

USAGE
  prismic page-type disconnect-slice <type-id> <slice-id> [flags]

ARGUMENTS
  type-id                Page type identifier (required)
  slice-id               Slice identifier (required)

Types are generated by default after changes. Use --no-types to skip.

FLAGS
  -z, --slice-zone string  Target slice zone field ID (default: "slices")
      --types string   Output file for generated types (default: "prismicio-types.d.ts")
      --no-types       Skip type generation
  -h, --help               Show help for command

EXAMPLES
  prismic page-type disconnect-slice homepage CallToAction
  prismic page-type disconnect-slice homepage CallToAction --slice-zone slices
  prismic page-type disconnect-slice article HeroSection -z body
`.trim();

const CustomTypeSchema = v.object({
	id: v.string(),
	label: v.string(),
	repeatable: v.boolean(),
	status: v.boolean(),
	format: v.string(),
	json: v.record(v.string(), v.record(v.string(), v.unknown())),
});

export async function pageTypeDisconnectSlice(): Promise<void> {
	const {
		values: { help, "slice-zone": sliceZoneId, types, "no-types": noTypes },
		positionals: [typeId, sliceId],
	} = parseArgs({
		args: process.argv.slice(4), // skip: node, script, "page-type", "disconnect-slice"
		options: {
			"slice-zone": { type: "string", short: "z" },
			types: { type: "string" },
			"no-types": { type: "boolean" },
			help: { type: "boolean", short: "h" },
		},
		allowPositionals: true,
	});

	if (help) {
		console.info(HELP);
		return;
	}

	if (!typeId) {
		console.error("Missing required argument: type-id\n");
		console.error("Usage: prismic page-type disconnect-slice <type-id> <slice-id>");
		process.exitCode = 1;
		return;
	}

	if (!sliceId) {
		console.error("Missing required argument: slice-id\n");
		console.error("Usage: prismic page-type disconnect-slice <type-id> <slice-id>");
		process.exitCode = 1;
		return;
	}

	// Find the page type file
	const projectRoot = await findUpward("package.json");
	if (!projectRoot) {
		console.error("Could not find project root (no package.json found)");
		process.exitCode = 1;
		return;
	}

	const modelPath = new URL(`customtypes/${typeId}/index.json`, projectRoot);

	// Read and parse the model
	let model: CustomType;
	try {
		const contents = await readFile(modelPath, "utf8");
		const result = v.safeParse(CustomTypeSchema, JSON.parse(contents));
		if (!result.success) {
			console.error(`Invalid page type model: ${modelPath.href}`);
			process.exitCode = 1;
			return;
		}
		model = result.output as CustomType;
	} catch (error) {
		if (error instanceof Error && "code" in error && error.code === "ENOENT") {
			console.error(`Page type not found: ${typeId}\n`);
			console.error(`Create it first with: prismic page-type create ${typeId}`);
			process.exitCode = 1;
			return;
		}
		if (error instanceof Error) {
			console.error(`Failed to read page type: ${error.message}`);
		} else {
			console.error("Failed to read page type");
		}
		process.exitCode = 1;
		return;
	}

	const targetSliceZoneId = sliceZoneId ?? "slices";

	// Find existing slice zone
	let sliceZone: DynamicSlices | undefined;
	let sliceZoneFieldId: string | undefined;

	// Search all tabs for a Slices field matching the target ID
	for (const [, tabFields] of Object.entries(model.json)) {
		for (const [fieldId, field] of Object.entries(tabFields)) {
			if ((field as { type?: string }).type === "Slices" && fieldId === targetSliceZoneId) {
				sliceZone = field as DynamicSlices;
				sliceZoneFieldId = fieldId;
				break;
			}
		}
		if (sliceZone) break;
	}

	// Slice zone must exist for disconnect
	if (!sliceZone) {
		console.error(`Slice zone "${targetSliceZoneId}" not found in page type "${typeId}"`);
		process.exitCode = 1;
		return;
	}

	// Check if slice is connected
	if (!sliceZone.config?.choices || !(sliceId in sliceZone.config.choices)) {
		console.error(
			`Slice "${sliceId}" is not connected to slice zone "${sliceZoneFieldId}" in ${typeId}`,
		);
		process.exitCode = 1;
		return;
	}

	// Remove the slice reference
	delete sliceZone.config.choices[sliceId];

	// Write updated model
	try {
		await writeFile(modelPath, stringify(model));
	} catch (error) {
		if (error instanceof Error) {
			console.error(`Failed to update page type: ${error.message}`);
		} else {
			console.error("Failed to update page type");
		}
		process.exitCode = 1;
		return;
	}

	console.info(
		`Disconnected slice "${sliceId}" from slice zone "${sliceZoneFieldId}" in ${typeId}`,
	);

	if (!noTypes) {
		try {
			await buildTypes({ output: types });
			console.info(`Updated types in ${types ?? "prismicio-types.d.ts"}`);
		} catch (error) {
			console.warn(`Could not generate types: ${error instanceof Error ? error.message : error}`);
		}
	}
}
